logfilename = /tmp/upmpdcli.log
loglevel = 2
pkgdatadir=/usr/local/share/upmpdcli
friendlyname = bee
upnpav = 0
openhome = 1
checkcontentformat = 0
cachedir = /home/giacomo/.cache/upmpdcli
mpdhost = localhost
mpdport = 6600
radiolist = /usr/local/share/upmpdcli/radio_scripts/radiolist.conf
qobuzuser = xxx
qobuzpass = yyy
qobuzformatid = 27
