# /usr/local/etc/musicpd.conf
# musicpd_enable="YES" in /etc/rc.conf

follow_outside_symlinks         "yes"
follow_inside_symlinks  "yes"
db_file         "/var/mpd/mpd.db"
log_file        "/var/mpd/mpd.log"
pid_file        "/var/mpd/pid"
music_directory         "/var/mpd/musica"
# playlist_directory      "/var/mpd/playlists"
state_file      "/var/mpd/mpdstate"
user    "mpd"
bind_to_address         "0.0.0.0"
port    "6600"
log_level       "default"
volume_normalization    "no"
audio_buffer_size       "16384"
buffer_before_play      "20%"
filesystem_charset      "UTF-8"
id3v1_encoding  "UTF-8"
gapless_mp3_playback    "yes"
auto_update     "no"
mixer_type      "disabled"
group   "mpd"
max_connections "20"
restore_paused "yes"
#
#
audio_output {
        type "oss"
        name "OKTO-DAC"
        device "/dev/dsp0"
        mixer_type        "none"
}
audio_output {
        enabled "no"
        type "oss"
        name "OKTO-DAC-0.05us_buf"
        device "/dev/dsp0"
        mixer_type        "none"
#        dsd_usb           "no"
        buffer_time       "50000"
        period_time       "256000000"
}


audio_output {
        type "oss"
        name "DAC+DRC"
        device "/dev/dsp0"
        enabled "no"
        mixer_type        "none"
#        dsd_usb           "no"
}

# audio_output {
#        type "oss"
#        name "Bryston BDA-2 + resampler"
#        device "/dev/dsp0"
#       format "192000:24:2"
#       enabled "no"
#        mixer_type        "none"
# }
