follow_inside_symlinks  "yes"
db_file         "/home/giacomo/.local/share/mpd/mpd.db"
log_file        "/home/giacomo/.local/share/mpd/mpd.log"
pid_file        "/home/giacomo/.cache/mpd/pid"
music_directory         "/media/USBHD2/musica"
state_file      "/home/giacomo/.local/share/mpd/mpdstate"
user    "giacomo"
bind_to_address         "0.0.0.0"
port    "6600"
log_level       "default"
volume_normalization    "no"
audio_buffer_size       "16384"
filesystem_charset      "UTF-8"
auto_update     "no"
mixer_type      "disabled"
group   "giacomo"
max_connections "20"
restore_paused "yes"

resampler {
  plugin "soxr"
  quality "very high"
}

audio_output {
        type "oss"
        name "OKTO-DAC"
        device "/dev/dsp0"
        mixer_type        "none"
}

audio_output {
        type "oss"
        name "DRC-native"
        device "/dev/dsp.play"
        format "*:*:*"
        enabled "no"
        mixer_type        "none"
}

audio_output {
        type "oss"
        name "DRC-resamp"
        device "/dev/dsp.play"
        format "192000:24:2"
        enabled "no"
        mixer_type        "none"
}
