hostname="bee"
wlans_iwm0="wlan0"
ifconfig_wlan0="WPA  DHCP"
ifconfig_wlan0_ipv6="inet6 ifdisabled  -auto_linklocal"
sshd_enable="YES"
ntpd_enable="YES"
dumpdev="AUTO"
dbus_enable="YES"
seatd_enable="YES"
sddm_enable="YES"
musicpd_enable="YES"
upmpdcli_enable="YES"
drc_usb_audio_enable="YES"
linux_enable="YES"
kld_list="fusefs i915kms"
omdrcctrl_enable="YES"
omdrcctrl_user="giacomo"
