notify 100 {
	match "system" "USB";
	match "subsystem" "INTERFACE";
	match "type" "ATTACH";
	match "intclass" "0x01";
	action "/usr/sbin/service drc_usb_audio onestart";
};

notify 100 {
	match "system" "USB";
	match "subsystem" "DEVICE";
	match "type" "DETACH";
	action "/usr/sbin/service drc_usb_audio onestop";
};
