[monitor]
topcpu_threshold = 4.0
monitor_interval = 5
topcpu_interval = 5
sndstat_interval = 5
brutefir_interval = 5

[qconnect]
status_file = /tmp/qconnect2mpd-status.txt
log_file    = /tmp/qconnect2mpd.log

[drc_status]
what    = Active config
group   = drc
type    = READ
refresh = 5
cmd     = /home/giacomo/open-media-drc/drc-status.sh

[drc_off]
what    = No DRC
group   = drc
type    = WRITE
button  = Apply
cmd     = /home/giacomo/open-media-drc/drc.sh off
process = brutefir

[drc_resamp]
what    = DRC Flat (0 dB) — auto resample
group   = drc
type    = WRITE
button  = Apply
cmd     = /home/giacomo/open-media-drc/drc.sh resamp
process = brutefir
details_link = https://github.com/delleceste/DRC-120.blue/tree/master/README.md

[drc_192000]
what    = DRC 192 kHz
group   = drc
type    = WRITE
button  = Apply
cmd     = /home/giacomo/open-media-drc/drc.sh 192000
process = brutefir

[drc_96000]
what    = DRC 96 kHz
group   = drc
type    = WRITE
button  = Apply
cmd     = /home/giacomo/open-media-drc/drc.sh 96000
process = brutefir

[drc_88200]
what    = DRC 88.2 kHz
group   = drc
type    = WRITE
button  = Apply
cmd     = /home/giacomo/open-media-drc/drc.sh 88200
process = brutefir

[drc_48000]
what    = DRC 48 kHz
group   = drc
type    = WRITE
button  = Apply
cmd     = /home/giacomo/open-media-drc/drc.sh 48000
process = brutefir

[drc_44100]
what    = DRC 44.1 kHz
group   = drc
type    = WRITE
button  = Apply
cmd     = /home/giacomo/open-media-drc/drc.sh 44100
process = brutefir

[drc_192000_2dB]
what    = DRC +2 dB / 192 kHz
group   = drc
type    = WRITE
button  = Apply
cmd     = /home/giacomo/open-media-drc/drc.sh 192000 +2dB
process = brutefir

[chrome]
what   = Google Chrome
group  = apps
type   = WRITE
button = Launch
cmd    = google-chrome

[kodi]
what   = Kodi media center
group  = apps
type   = WRITE
button = Launch
cmd    = kodi

[reboot]
what    = Reboot system
group   = system
type    = WRITE
button  = Reboot
confirm = yes
cmd     = sudo reboot

[poweroff]
what    = Power off
group   = system
type    = WRITE
button  = Off
confirm = yes
cmd     = sudo poweroff
